name: Bien
favicon: null
layout_spectrum: 0.8751874924637377
typography_spectrum: 0.7547327266074717
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.02671820274554193
  lightness: 0.9357141752261668
  saturation: 0.6686562274117023
  rhythmicContrast: 0.11419801274314523
purpose: []
